const constants = {
    FETCH_USER: 'FETCH_USER',
    FETCH_USER_REPOSITORIES: 'FETCH_USER_REPOSITORIES',
    FETCH_USER_FOLLOWERS: 'FETCH_USER_FOLLOWERS',
    FETCH_USER_ORGS: 'FETCH_USER_ORGS',
    FETCH_USER_FAILED: 'FETCH_USER_FAILED'
}
export default constants
